#!/bin/bash

# Demostración del flujo de trabajo real del examshell con 3 terminales

echo "🎯 EXAMSHELL - Real 3-Terminal Workflow Demo"
echo "=============================================="
echo ""
echo "Este script demuestra el flujo de trabajo REAL del examshell de 42:"
echo ""
echo "📊 TERMINAL SETUP:"
echo "┌─────────────────────────────────────────────────────────────┐"
echo "│ Terminal 1: EXAMSHELL CONTROL                              │"
echo "│ - ./examshell 03                                           │"
echo "│ - Navegación del examen ([g], [n], [q])                   │"
echo "│ - NO muestra el subject                                    │"
echo "├─────────────────────────────────────────────────────────────┤"
echo "│ Terminal 2: READ SUBJECT                                   │"
echo "│ - cat subject/[exercise-name]/subject.txt                  │"
echo "│ - Leer instrucciones del ejercicio                        │"
echo "│ - Consultar cuando sea necesario                          │"
echo "├─────────────────────────────────────────────────────────────┤"
echo "│ Terminal 3: CODE & TEST                                    │"
echo "│ - vim [exercise-name].c                                    │"
echo "│ - gcc [exercise-name].c                                    │"
echo "│ - ./a.out                                                  │"
echo "└─────────────────────────────────────────────────────────────┘"
echo ""
echo "🔥 DIFERENCIAS CON EL SISTEMA ANTERIOR:"
echo "❌ Antes: Subject se mostraba automáticamente"
echo "✅ Ahora: Debes ir a buscarlo a subject/[name]/subject.txt"
echo ""
echo "❌ Antes: Todo en 1 terminal"
echo "✅ Ahora: Workflow real de 3 terminales"
echo ""
echo "❌ Antes: Fácil acceso al subject"
echo "✅ Ahora: Como en examen real - tienes que gestionarlo"
echo ""
echo "📝 COMANDOS PARA PROBAR:"
echo ""
echo "# Terminal 1 - Control del examen:"
echo "make && ./examshell 03"
echo ""
echo "# Terminal 2 - Cuando aparezca un ejercicio (ej: filter):"
echo "cat subject/filter/subject.txt"
echo ""
echo "# Terminal 3 - Desarrollo:"
echo "vim filter.c"
echo "gcc filter.c"
echo "./a.out"
echo ""
echo "🎊 EXPERIENCIA 100% REAL DEL EXAMSHELL!"
echo ""
echo "Ready to test the real examshell experience!"
