#!/bin/bash

# Demostración de la nueva interfaz con subject automático

echo "==================================="
echo "        42 SCHOOL - EXAMSHELL        "
echo "         Practice Environment        "
echo "==================================="
echo ""
echo "EXAM RANK 03 - LEVEL 1"
echo "EXAM MODE: 1 exercise per level (like real exam)"
echo "Status: Working on level 1 exercise"
echo ""
echo "📚 Current Exercise:"
echo "   Name: filter"
echo "   Level: 1"
echo "   Path: ./exam-rank-03/level-1/filter"
echo ""
echo -e "\033[33m=== SUBJECT ===\033[0m"
echo ""
echo "Assignment name: filter"
echo "Expected files: filter.c"
echo "Allowed functions: read, write, strlen, memmem, memmove, malloc, calloc,"
echo "realloc, free, printf, fprintf, stdout, stderr, perror"
echo "--------------------------------------------------------------------------------"
echo ""
echo "Write a program that will take one and only one argument."
echo ""
echo "Your program will then read from stdin and write all the content read in stdout"
echo "except that every occurrence of s must be replaced by '*' (as many as the length"
echo "of s). Your program will be tested with random buffer sizes, using a custom read"
echo "function. Therefore the buffer being set in your program will be filled with a"
echo "different number of chars each new call."
echo ""
echo "For example:"
echo ""
echo "./filter bonjour"
echo "will behave in the same way as:"
echo "sed 's/bonjour/*******/g'"
echo ""
echo -e "\033[33m=== END SUBJECT ===\033[0m"
echo ""
echo "Press Enter to continue to menu..."
read
echo ""
echo "Available options:"
echo "  [t] Run tester (coming soon)"
echo "  [g] Grademe - Mark as passed"
echo "  [n] Next exercise (same level)"
echo "  [q] Quit"
echo ""
echo -n "Enter your choice: "
